### ISSUE TITLE
Improve missing heartbeat handling

### ISSUE THREAD

**Issue by PiotrDuz** [kagkarlsson/db-scheduler#402] opened 2023-06-13 08:06 UTC
Hello,
I have noticed than if the instance currently having the lock misses heartbeats for some reason (freezes, network issue etc), the lock may timeout and open up. This can lead to other instance starting using the lock. What if the frozen instance recovers and starts using the same lock too? 

Can we implement some sort of a callback to be called when sending a heartbeat falls? This callback would just cancel the process and the instance would lose its lock, lock would have to be acquired again.

What do you guys think? Is the missed heartbeat situation a possible bug?

**Comment by kagkarlsson** [comment] 2023-06-13 13:56
It has to miss a couple of heartbeats to be considered dead.

```
  Duration getMaxAgeBeforeConsideredDead() {
    return heartbeatInterval.multipliedBy(4);
  }
```

Registering a heartbeat should never fail. If it does I suggest looking at the cause rather than adding callback support for failed heartbeats. What is the error you got for the heartbeats? If you get a timeout due the query being heavy (due large volume of executions in table), it might help adding indices.

You might add custom logic via a `DeadExecutionHandler`.

**Comment by PiotrDuz** [comment] 2023-06-13 14:08
Thanks for an answer.
We are interested in using this library but we would like to know what are its weak spots. 
Lets create here a hypothetical scenario:
Node A and Node B are on separate machines. They are using the same database, on another machine. 
Lets assume that node A started long-lasting process. It has the lock now and send heartbeats. 
Suddenly internet connection is down for machine A. The process is still running, it might be using some other service that is still reachable or wait for connection to DB to come back. 
Now, lock that machine A had will timeout. Machine B will acquire the lock and restart unfinished process. 
Now we have 2 processes running simultaneously on both machines. Connection on machine running  node A might come back at some point. 

Dont get me wrong, library already solves a lot of issues with distributed systems. But arent we leaving here an open door for a failure? 
Regards

**Comment by PiotrDuz** [comment] 2023-06-17 13:55
@kagkarlsson would you accept a PR regarding this issue if I were to prepare one?
Regards

**Comment by kagkarlsson** [comment] 2023-06-19 13:48
I am not sure we already have everything we need here. 

> This callback would just cancel the process and the instance would lose its lock, lock would have to be acquired again.

How will you reliably cancel the process?

If you are very concerned, you can change to a `DeadExecutionHandler` that just removes the execution and logs a manual followup or something like that.

**Comment by PiotrDuz** [comment] 2023-06-19 13:55
I would leave process cancellation to the user who implement it. That why I want it to be a callback. 
For example, reactive java stream already provide a handler (dosposable) to cancel the stream easily. 

Manual intervention to resolve possible conflict is a way here, but wouldn't it be better to have library do it for us?
Anyways, thanks for a response and I understand that as a maintainer you have to wage features vs maintenance .

**Comment by eyalschneider** [comment] 2023-08-30 10:28
I am still not familiar with all APIs and implementation details, but please consider this solution for mitigating the risk of concurrent work on the same task:
1. The heartbeat producer background thread should be aware of two possible error scenarios: a) A sequence of IO errors for a period that exceeds the allowed one b) Heartbeat update worked, but detects a conflict: somebody else has already taken the task.
2. Once either of the error scenarios is detected, a state variable should be updates locally (inside the task's execution context)
3. It's the responsibility of the task implementation to check the lock ownership state (as reflected in the context object) at strategic locations, and abort if it detects that the task isn't owned anymore.

This doesn't solve the issue completely (I don't think there exist a perfect solution for the described situation in a distributed environment). However, it reduces the time it takes for the worker to realize that it should abort the task execution. What do you think?

**Comment by kagkarlsson** [comment] 2023-08-30 12:13
Concretely, what type of errors have you seen causing failed heartbeats?

**Comment by kagkarlsson** [comment] 2023-08-31 06:17
Heads-up though, I am not sure when I will get the time to work on this. Your best option might be to try and contribute the most important missing pieces.

**Comment by kagkarlsson** [comment] 2023-10-25 15:44
Started looking at implementing something simple for this here: #432

**Comment by kagkarlsson** [comment] 2024-04-18 18:24
Improved heartbeat-handling in #432. Hopefully that has something you can work with. Closing this issue.

**Closed by kagkarlsson** 2024-04-18 18:24 UTC
Labels: enhancement, pri1

**Comment by PiotrDuz** [comment] 2024-04-18 18:39
@kagkarlsson  thank you for heads up!
Sorry for my absence, I am working now on different project that is not using dbscheduler but quartz. Well I have to say I miss working with dbscheduler as it is way easier to handle  :)
Regards

**Comment by kagkarlsson** [comment] 2024-04-19 06:38
Good to hear @PiotrDuz :)
